[deps]
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Mera = "02f895e8-fdb1-4346-8fe6-c721699f5126"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
julia = "1.6"
